# Generated by Django 3.1.5 on 2021-02-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210203_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availble_display',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='default',
        ),
        migrations.AddField(
            model_name='product',
            name='available_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product'),
        ),
    ]
