# Generated by Django 3.1.5 on 2021-02-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210203_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availble_display',
            new_name='available_display',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='default',
        ),
    ]
